### PR TITLE
0002 Recipe introduction section

### PR DESCRIPTION
**Pull request by pelted**
[Rendered](https://github.com/pelted/cooklang-spec/blob/pelted/add-recipe-introduction-proposal/proposals/0002-add-recipe-introduction-section.md)

From [CONTRIBUTING.md](https://github.com/cooklang/spec/blob/main/CONTRIBUTING.md)

This PR is a proposal submission to add support for an introduction section to a recipe and to facilitate defining ingredients at the top of a `.cook` file.

See discussion #46

### CODE REVIEW

**Comment by pelted** [comment]
I was just looking at [cooklang-swift](https://github.com/cooklang/cooklang-swift) and maybe it would be easier to do pre-defined ingredients with the comment syntax.

```cooklang
>> source: https://www.joshuaweissman.com/post/easy-authentic-thai-green-curry

== Homemade Thai Green Curry deserves respect when making it.
== Good thing it's actually very easy and just requires a little elbow grease.

-- @coriander seeds{2%tsps}
-- @cumin seeds{1%tsps}
-- @white peppercorn{1%tsps}

First step goes here
```

**Comment by pubmania** [comment]
I think I can see the benefit of an introduction section but having ingredients block separated out is lost on me. Woulpd you be able to explain why this may be desirable? 

One of the things that attracted me to cooklang was the fact that I dont have to write ingredients and steps separately and then every time jump between two sections. On the presentation layer (UI) it can be and is presented with two separate blocks but at the time of writing the .cook file or in my case the cooklang codeblock, I think it will add unwanted complexity but perhaps there may be an advantage to this approach which I am unable to grasp, hence the question.

**Comment by dubadub** [comment]
I think there're two separate proposals here which should be discussed separately. I think it's a valid use case to have some recipe description. That can be done now with notes or we can add canonical description tag into https://github.com/cooklang/spec/pull/105.

```cooklang
---
source: https://www.joshuaweissman.com/post/easy-authentic-thai-green-curry
description: |
    Homemade Thai Green Curry deserves respect when making it.
    Good thing it's actually very easy and just requires a little elbow grease.
---

First step goes here
```

or 

```cooklang
---
source: https://www.joshuaweissman.com/post/easy-authentic-thai-green-curry
---
> Homemade Thai Green Curry deserves respect when making it.
> Good thing it's actually very easy and just requires a little elbow grease.

First step goes here
```

**Comment by dubadub** [comment]
As for the listing ingredients in front, I don't think that I understand the motivation...

**Pull request merged**
